export const FETCH_POKEMONS_PAGE_STARTED = 'FETCH_POKEMONS_PAGE_STARTED';
export const FETCH_POKEMONS_PAGE_SUCCESS = 'FETCH_POKEMONS_PAGE_SUCCESS';
export const FETCH_POKEMONS_PAGE_FAILED = 'FETCH_POKEMONS_PAGE_FAILED';
export const FETCH_SINGLE_POKEMON_STARTED = 'FETCH_SINGLE_POKEMON_STARTED';
export const FETCH_SINGLE_POKEMON_SUCCESS = 'FETCH_SINGLE_POKEMON_SUCCESS';
export const FETCH_SINGLE_POKEMON_FAILED = 'FETCH_SINGLE_POKEMON_FAILED';
export const DISPLAY_MODAL = 'DISPLAY_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';
